export * from "./Comments"
export * from "./CustomerRecord"
export * from "./ItemDishes"
export * from "./ListDishes"
export * from "./list-Left"
export * from "./list-Right"
export * from "./Login"
export * from "./Ticket"